[package]
name = "solve_many_linsys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msgpass = "0.4"
plotpy = "0.5"
rayon = "1.8"
russell_lab = "0.7"
russell_sparse = "0.7"
structopt = "0.3"
